version: '2'
services:
    ansiblecontroller:
        image: ansibletemplate
        restart: always
        entrypoint: 
        - /usr/sbin/sshd 
        - -D 
        volumes:
            - ./data/controller/logs:/opt/logs
            - ./data/controller/store:/store
    target1:
        image: ansibletemplate
        restart: always
        entrypoint: 
        - /usr/sbin/sshd 
        - -D 
        volumes:
            - ./data/target/logs:/opt/logs
            - ./data/target/store:/store
        depends_on:
          - ansiblecontroller
