version: '2'
services:
    ansiblecontroller:
        image: ansibletemplate
        restart: always
        entrypoint: 
        - /bin/bash
        - -c 
        - "trap : TERM INT; sleep infinity & wait"
    target1:
        image: ansibletemplate
        restart: always
        entrypoint: 
        - /bin/bash
        - -c 
        - "trap : TERM INT; sleep infinity & wait"
        depends_on:
          - ansiblecontroller
